version: '3.3'

services:

    nginx:
        build:
           context: ./nginx
           dockerfile: Dockerfile
        ports:
            - '127.0.0.1:1235:80'
        volumes:
            - './nginx/html:/usr/local/nginx/html'
        restart: unless-stopped
        networks:
            - backend


networks:
    backend:
    
